#
# Ardufocus - Moonlite compatible focuser
# Copyright (C) 2017 João Brázio [joao@brazio.org]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

sudo: false
language: python

python:
    - "2.7"

before_install:
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  - export PATH=${TRAVIS_BUILD_DIR}/buildroot/bin/:${PATH}

install:
  - pip install -U platformio

before_script:
  - cd ${TRAVIS_BUILD_DIR}

script:
  #- set -e
  #
  # Test default config
  - platformio run -e debug -e debug168
  #
  # Test basic A4988 driver
  - config-header
  - config-opt-add MOTOR1_USE_A4988_DRIVER
  - config-opt-add MOTOR1_PINOUT "12, 11, 10, 8, 7, 6"
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  - config-header
  - config-opt-add MOTOR1_USE_A4988_DRIVER
  - config-opt-add MOTOR1_PINOUT "12, 11, 10, 8, 7, 6"
  - config-opt-add MOTOR1_INVERT_DIRECTION
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  - config-header
  - config-opt-add MOTOR1_USE_A4988_DRIVER
  - config-opt-add MOTOR1_PINOUT "12, 11, 10, 8, 7, 6"
  - config-opt-add MOTOR1_INVERT_DIRECTION
  - config-opt-add MOTOR1_SLEEP_WHEN_IDLE
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  - config-header
  - config-opt-add MOTOR1_USE_A4988_DRIVER
  - config-opt-add MOTOR1_PINOUT "12, 11, 10, 8, 7, 6"
  - config-opt-add MOTOR1_INVERT_DIRECTION
  - config-opt-add MOTOR1_SLEEP_WHEN_IDLE
  - config-opt-add MOTOR1_COMPRESS_STEPS
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  - config-header
  - config-opt-add MOTOR1_USE_A4988_DRIVER
  - config-opt-add MOTOR1_PINOUT "12, 11, 10, 8, 7, 6"
  - config-opt-add MOTOR1_INVERT_DIRECTION
  - config-opt-add MOTOR1_SLEEP_WHEN_IDLE
  - config-opt-add MOTOR1_COMPRESS_STEPS
  - config-opt-add START_TEMP_CONVERSION_ON_EVERY_GET
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  # Test basic ULN2003 driver
  - config-header
  - config-opt-add MOTOR1_USE_ULN2003_DRIVER
  - config-opt-add MOTOR1_PINOUT "2, 3, 4, 5"
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  - config-header
  - config-opt-add MOTOR1_USE_ULN2003_DRIVER
  - config-opt-add MOTOR1_PINOUT "2, 3, 4, 5"
  - config-opt-add MOTOR1_INVERT_DIRECTION
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  - config-header
  - config-opt-add MOTOR1_USE_ULN2003_DRIVER
  - config-opt-add MOTOR1_PINOUT "2, 3, 4, 5"
  - config-opt-add MOTOR1_INVERT_DIRECTION
  - config-opt-add MOTOR1_SLEEP_WHEN_IDLE
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  - config-header
  - config-opt-add MOTOR1_USE_ULN2003_DRIVER
  - config-opt-add MOTOR1_PINOUT "2, 3, 4, 5"
  - config-opt-add MOTOR1_INVERT_DIRECTION
  - config-opt-add MOTOR1_SLEEP_WHEN_IDLE
  #- config-opt-add MOTOR1_COMPRESS_STEPS
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  - config-header
  - config-opt-add MOTOR1_USE_ULN2003_DRIVER
  - config-opt-add MOTOR1_PINOUT "2, 3, 4, 5"
  - config-opt-add MOTOR1_INVERT_DIRECTION
  - config-opt-add MOTOR1_SLEEP_WHEN_IDLE
  #- config-opt-add MOTOR1_COMPRESS_STEPS
  - config-opt-add START_TEMP_CONVERSION_ON_EVERY_GET
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  # Test A4988 with acceleration
  - config-header
  - config-opt-add MOTOR1_USE_A4988_DRIVER
  - config-opt-add MOTOR1_PINOUT "12, 11, 10, 8, 7, 6"
  - config-opt-add USE_LINEAR_ACCEL
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  - config-header
  - config-opt-add MOTOR1_USE_A4988_DRIVER
  - config-opt-add MOTOR1_PINOUT "12, 11, 10, 8, 7, 6"
  - config-opt-add USE_TRAPEZOID_ACCEL
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  - config-header
  - config-opt-add MOTOR1_USE_A4988_DRIVER
  - config-opt-add MOTOR1_PINOUT "12, 11, 10, 8, 7, 6"
  - config-opt-add USE_SMOOTHSTEP_ACCEL
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  # Test ULN2003 with acceleration
  - config-header
  - config-opt-add MOTOR1_USE_ULN2003_DRIVER
  - config-opt-add MOTOR1_PINOUT "2, 3, 4, 5"
  - config-opt-add USE_LINEAR_ACCEL
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  - config-header
  - config-opt-add MOTOR1_USE_ULN2003_DRIVER
  - config-opt-add MOTOR1_PINOUT "2, 3, 4, 5"
  - config-opt-add USE_TRAPEZOID_ACCEL
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
  #
  - config-header
  - config-opt-add MOTOR1_USE_ULN2003_DRIVER
  - config-opt-add MOTOR1_PINOUT "2, 3, 4, 5"
  - config-opt-add USE_SMOOTHSTEP_ACCEL
  - config-ntc
  - config-footer
  - platformio run -e debug -e debug168
